name: Olive and Bear
favicon: null
layout_spectrum: 0.2582241261843592
typography_spectrum: 0.439581855898723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f2e7'
    - '#262729'
    - '#8b8b8b'
    - '#f89dc6'
    - '#cb405d'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
