name: Olive and Bear
favicon: null
layout_spectrum: 0.2582241261843592
typography_spectrum: 0.439581855898723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.42954744887538254
  lightness: 0.014012569095939398
  saturation: 0.08006667997688055
  rhythmicContrast: 0.9926632456481457
purpose: []
